// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.871
package history

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func History() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4 pt-8 md:max-w-[50%]\"><!-- Row 1: Image left, Text right --><div class=\"md:flex md:items-center md:gap-8 mb-8\"><div class=\"md:w-1/2 mb-4 md:mb-0\"><img src=\"/static/assets/img/history1.jpg\" alt=\"Bild 1\" class=\"rounded shadow w-full\"></div><div class=\"md:w-1/2\"><h3 class=\"text-xl font-semibold mb-2\">Så träffades vi</h3><p>Det var en gång två själar som fann varandra på en oväntad plats. Resten är, som man säger, historia!</p></div></div><!-- Row 2: Text left, Image right --><div class=\"md:flex md:flex-row-reverse md:items-center md:gap-8 mb-8\"><div class=\"md:w-1/2 mb-4 md:mb-0\"><img src=\"/static/assets/img/history2.jpg\" alt=\"Bild 2\" class=\"rounded shadow w-full\"></div><div class=\"md:w-1/2\"><h3 class=\"text-xl font-semibold mb-2\">Första dejten</h3><p>En kväll fylld av skratt, god mat och pirr i magen. Vi visste direkt att detta var något speciellt.</p></div></div><!-- Row 3: Image left, Text right --><div class=\"md:flex md:items-center md:gap-8 mb-8\"><div class=\"md:w-1/2 mb-4 md:mb-0\"><img src=\"/static/assets/img/history3.jpg\" alt=\"Bild 3\" class=\"rounded shadow w-full\"></div><div class=\"md:w-1/2\"><h3 class=\"text-xl font-semibold mb-2\">Och nu...</h3><p>Tillsammans ser vi fram emot ett liv fyllt av kärlek, äventyr och många fler minnen!</p></div></div><!-- Row 4: Text left, Image right --><div class=\"md:flex md:flex-row-reverse md:items-center md:gap-8 mb-8\"><div class=\"md:w-1/2 mb-4 md:mb-0\"><img src=\"/static/assets/img/history2.jpg\" alt=\"Bild 4\" class=\"rounded shadow w-full\"></div><div class=\"md:w-1/2\"><h3 class=\"text-xl font-semibold mb-2\">FJÄRDE PARAGRAPH dejten</h3><p>En kväll fylld av skratt, god mat och pirr i magen. Vi visste direkt att detta var något speciellt.</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
