// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.871
package rsvp

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func OsaForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form hx-post=\"/osa\" hx-swap=\"innerHTML\" hx-target=\"#osa-form\" hx-ext=\"form-json\" class=\"space-y-4 max-w-full\"><fieldset class=\"form-control0\"><label class=\"label\"><span class=\"label-text\">Gäster <span class=\"text-xs opacity-60\">(lägg till en ruta per person)</span></span></label><div id=\"people-grid\" class=\"grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3 place-items-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = AddPersonTile().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></fieldset><div class=\"form-control\"><input type=\"email\" name=\"email\" placeholder=\"E-post\" required class=\"input input-bordered w-full peer invalid:border-red-500 focus:invalid:border-red-500\"> <span class=\"mt-1 text-sm text-red-500 invisible peer-invalid:visible\">Ange en giltig e-postadress</span></div><div class=\"form-control\"><label class=\"label cursor-pointer\"><input type=\"radio\" name=\"coming\" value=\"yes\" class=\"radio checked:bg-yellow-600\"> <span class=\"label-text ml-2\">Vi kommer</span></label> <label class=\"label cursor-pointer\"><input type=\"radio\" name=\"coming\" value=\"no\" class=\"radio checked:bg-yellow-600\"> <span class=\"label-text ml-2 break-words whitespace-normal\">Tyvärr kommer vi inte närvara</span></label></div><textarea name=\"message\" placeholder=\"Meddelande\" class=\"textarea textarea-bordered w-full max-w-full min-w-0 h-32\"></textarea> <button type=\"submit\" class=\"btn btn-outline btn-primary\">Skicka Anmälan</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func PersonTile() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"person-tile relative overflow-visible flex flex-col items-center gap-2\n              p-4 pt-8 pr-8 rounded-2xl border border-base-300 bg-base-100\n              w-full max-w-xs\"><button type=\"button\" aria-label=\"Ta bort\" class=\"absolute top-2 right-2 z-30 pointer-events-auto grid h-6 w-6 place-items-center\n             rounded-full border border-base-300 bg-base-100 text-base-content/80\n             hover:bg-base-200 hover:text-base-content shadow-sm\" hx-on:click=\"this.closest(&#39;.person-tile&#39;)?.remove()\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" class=\"h-3.5 w-3.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M6 6l12 12M18 6L6 18\"></path></svg></button> <input type=\"text\" name=\"people[]\" placeholder=\"Namn\" minlength=\"2\" required aria-invalid=\"false\" oninput=\"this.setAttribute(&#39;aria-invalid&#39;, this.validity.valid ? &#39;false&#39; : &#39;true&#39;)\" onblur=\"this.setAttribute(&#39;aria-invalid&#39;, this.validity.valid ? &#39;false&#39; : &#39;true&#39;)\" class=\"peer input input-bordered input-sm w-full text-center\n             invalid:border-red-500 focus:invalid:border-red-500\"> <span class=\"hidden text-xs text-red-500 peer-aria-[invalid=true]:block\">Minst 2 tecken</span></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func AddPersonTile() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<button type=\"button\" class=\"flex flex-col items-center justify-center gap-2 w-full max-w-xs h-32\n           rounded-2xl border-2 border-dashed border-base-300\n           transition-transform duration-150 hover:scale-105\n           hover:border-primary hover:text-primary\" hx-get=\"/osa/people/new\" hx-target=\"this\" hx-swap=\"beforebegin\" hx-on:htmx:afterSwap=\"previousElementSibling?.querySelector(&#39;input&#39;)?.focus()\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" class=\"w-7 h-7\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.5\"><path d=\"M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z\"></path> <path d=\"M4.5 20.25a7.5 7.5 0 0 1 15 0\"></path> <path d=\"M19 7v4m2-2h-4\"></path></svg> <span class=\"text-sm\">Lägg till person</span></button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
