// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.871
package rsvp

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func RSVP() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4 py-8 md:max-w-[50%]\"><div class=\"grid grid-cols-1 md:grid-cols-1 gap-8\"><div><h2 class=\"text-3xl font-serif mb-2\">Vill ni vara med och förgylla våran stora dag?</h2><p class=\"mb-4\">Fyll i formuläret nedanför för att OSA. Senaste datumet att OSA är <strong>14 februari</strong>. Fyll i alla namn från ett och samma sällskap under <em>Ditt/era namn</em> samt en <em>E-post</em> till en av er.</p><p class=\"mb-4\">Under <em>Meddelande</em> kan får ni gärna skriva in om ni har eventuella allergier så att ni också kan få något att äta.</p><p class=\"text-sm italic\">Vill ni hålla tal eller spex, fyll även i formuläret <b>Tal & Spex</b>.</p></div><div id=\"osa-form\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = OsaForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"divider\">Tal & Spex</div><div><h2 class=\"text-3xl font-serif mb-2\">Vill du eller ni hålla tal?</h2><p class=\"mb-4\">Fyll i formuläret på nedanför för att ansöka om att hålla tal. Senaste datumet att registrera tal är <strong>20 Maj</strong>. Fyll i alla namn från ett och samma sällskap under <em>Ditt/era namn</em> samt en <em>E-post</em> till en av er. Det är endast våra Toastmasters som får dessa meddelanden och registreringar.</p><p class=\"mb-4\">Under <em>Meddelande</em> kan får ni har speciella frågor eller något ni vill meddela Toastmasters</p></div><div id=\"speach-form\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = SpeachForm().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
