// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.871
package faq

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Faq() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4 pt-8 md:max-w-[70%]\"><div class=\"join join-vertical w-full\"><div class=\"collapse collapse-arrow join-item border border-base-300\"><input type=\"checkbox\"><div class=\"collapse-title text-lg font-medium text-center\">När börjar vigseln?</div><div class=\"collapse-content\"><p class=\"text-center\">Vigseln börjar den 23e Maj 2026 kl 14:00 i Våxtorps Kyrka.</p></div></div><div class=\"collapse collapse-arrow join-item border border-base-300\"><input type=\"checkbox\"><div class=\"collapse-title text-lg font-medium text-center\">Finns det parkering vid kyrkan?</div><div class=\"collapse-content\"><p class=\"text-center\">Ja, det finns gott om parkering precis utanför kyrkan.</p></div></div><div class=\"collapse collapse-arrow join-item border border-base-300\"><input type=\"checkbox\"><div class=\"collapse-title text-lg font-medium text-center\">Hur anmäler jag allergier?</div><div class=\"collapse-content\"><p class=\"text-center\">Fyll i eventuella allergier i OSA-formuläret under \"Meddelande\".</p></div></div><div class=\"collapse collapse-arrow join-item border border-base-300\"><input type=\"checkbox\"><div class=\"collapse-title text-lg font-medium text-center\">Är barn välkomna till Festen?</div><div class=\"collapse-content\"><p class=\"text-center\">Inga barn är tyvärr välkomna till festen, undantag för ammanade bäbisar.</p></div></div><div class=\"collapse collapse-arrow join-item border border-base-300\"><input type=\"checkbox\"><div class=\"collapse-title text-lg font-medium text-center\">Kan jag ta med mig en +1?</div><div class=\"collapse-content\"><p class=\"text-center\">Kul att du vill ha med dig någon till festen! Tyvärr har vi plats brist och redan fått välja bort bland våra egna bekanta. Så, nej, inga +1:or</p></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
