// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.871
package weddingday

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func WeddingDay() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4 pt-8 md:max-w-[50%]\"><div class=\"flex justify-center\"><div class=\"text-center\"><h2 class=\"text-3xl font-serif mb-4\">Vår stora dag</h2><p class=\"mb-4\">Den <strong>23 maj 2026</strong> säger vi JA till varandra i vackra <strong>Våxtorps Kyrka</strong>!<br>Efter vigseln bjuder vi in till en hejdundrande fest på <strong>Äppelgårdens Golfkrog</strong> – där skratt, god mat och glada överraskningar väntar.<br></p><p class=\"mb-4\">Ta på dig ditt bästa humör, putsa dansskorna och gör dig redo för en dag vi sent kommer glömma.<br>Vi ser så mycket fram emot att fira denna speciella dag tillsammans med er alla!</p><p class=\"italic\">Kärlek, skratt och kanske en och annan dansmove utlovas!</p><p class=\"font-semibold mt-8 mb-2\">För att hitta till alla festligheter hittar ni här kartor – så ni inte råkar hamna på fel bröllop!</p><div class=\"my-6\"><iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2312.9228841096733!2d13.107423276840354!3d56.42270554019514!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x465177c1dba27c07%3A0x6b17c2a2c22deeb1!2sV%C3%A5xtorps%20kyrka!5e1!3m2!1ssv!2sse!4v1748617997063!5m2!1ssv!2sse\" width=\"100%\" height=\"350\" style=\"border:0; max-width:600px;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\" class=\"mx-auto block\"></iframe></div><div class=\"my-6\"><iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2312.8463952645507!2d12.923676976840456!3d56.42396334009751!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x465664039dda258f%3A0x3e299ab197abbe7b!2zw4RwcGVsZ8OlcmRlbg!5e1!3m2!1ssv!2sse!4v1748618080233!5m2!1ssv!2sse\" width=\"100%\" height=\"350\" style=\"border:0; max-width:600px;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\" class=\"mx-auto block\"></iframe></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
