// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.871
package weddingday

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func WeddingDay() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container mx-auto px-4 pt-8 md:max-w-[70%]\"><div class=\"flex justify-center\"><div class=\"text-center\"><h2 class=\"text-4xl font-serif mb-4\">Vår stora dag</h2><p class=\"text-xl mb-4\">Den <strong>23 maj 2026</strong> säger vi JA till varandra i vackra <strong>Våxtorps Kyrka</strong>!<br>Efter vigseln bjuder vi in till en hejdundrande fest på <strong>Äppelgårdens Golfkrog</strong> – där skratt, god mat och en fantastisk kväll väntar.<br></p><p class=\"text-xl mb-4\">Ta med dig ditt bästa humör, putsa dansskorna och gör dig redo för en dag vi sent kommer glömma.<br>Vi ser så mycket fram emot att fira denna speciella dag tillsammans med er alla!</p><p class=\"text-xl italic\">Kärlek, skratt och kanske ett och annat dansmove utlovas!</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
